### ISSUE TITLE
ultrasat issue

### ISSUE THREAD

**Issue by AkshayPanayada** [nasa/dorado-scheduling#91] opened 2023-11-12 19:58 UTC
I have tried dorado-scheduling with ultrasat as mission. The skymap was taken from ligo data. The .sh file used is attached
[test_dorado3.txt](https://github.com/nasa/dorado-scheduling/files/13328991/test_dorado3.txt)
I initially thought it was the issue with the fov. I modified it to the same as dorado and still recieved the error that RAM is insufficient. Once I also got a timeout error

**Comment by lpsinger** [comment] 2023-11-13 00:04
Is this a duplicate of #87?

**Comment by AkshayPanayada** [comment] 2023-11-15 15:16
This is kind of the same, but then other missions are working fine. To check if it is with the fov of ultrasat, I tried to change it and ran it again and still got the error

**Comment by lpsinger** [comment] 2024-04-16 22:04
Yes, I think that this is a memory issue. See my comments on https://github.com/nasa/dorado-scheduling/issues/87#issuecomment-2059991616 about memory usage.

**Closed by lpsinger** 2024-04-16 22:04 UTC
